# Generated by Django 2.2.5 on 2019-09-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='Links',
        ),
    ]
