# Generated by Django 2.2.5 on 2019-09-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20190923_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
