# Generated by Django 2.2.5 on 2019-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_auto_20190923_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
